version: "3.8"
services:

  client:
    build:
      context: ./Client
      dockerfile: ../Dockerfile # installs OpenTelemetry .NET Automatic Instrumentation
    entrypoint: "./out/Examples.Client http://service:5000"
    env_file:
      - otel-dotnet.env # enables OpenTelemetry .NET Automatic Instrumentation
    environment:
      # OpenTelemetry environmental variables:
      OTEL_SERVICE_NAME: "client"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    depends_on:
      - service
      - otel-collector

  service:
    build:
      context: ./Service
      dockerfile: ../Dockerfile # installs OpenTelemetry .NET Automatic Instrumentation
    entrypoint: "./out/Examples.Service --urls http://*:5000"
    env_file:
      - otel-dotnet.env # enable OpenTelemetry .NET Automatic Instrumentation
    environment:
      # OpenTelemetry environmental variables:
      OTEL_SERVICE_NAME: "service"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES: "Examples.Service"
      OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES: "Examples.Service"
    depends_on:
      - otel-collector
      

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
      - ./log:/log/otel
    command: --config /etc/otel/config.yaml
    ports:
      - "13133:13133" # health_check extension http://localhost:13133
      - "55679:55679" # ZPages extension
